# 🗄️ DATABASE (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.kogcjlxssgimucmhozyi
spring.datasource.password=springboot-demo123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ☁️ SUPABASE STORAGE CONFIG
supabase.url=https://kogcjlxssgimucmhozyi.supabase.co
supabase.bucket=uploads
supabase.apiKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZ2NqbHhzc2dpbXVjbWhvenlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDM0MTM3MSwiZXhwIjoyMDg5OTE3MzcxfQ.xJUdIjdCv8jCWAN9RQiEpdIXfWHTIzgVw4Px8DgZklA

# 🔐 JWT Secret
jwt.secret=ZNyQcy4mV4mMOzULTa9N7Alsxy2jQrT7FuZW3CHBqvhgbURv4xB2svoSv6pBfJ7S3TtS6a2kiSwK2aNVaF0J3Q==
jwt.expiration=86400000